fix(nvimgdb.vim): cleanup env if term exit
sakhnik/nvim-gdb pull request #148
Opened 2021-05-23 06:08 UTC by kevinhwang91

2021-05-23 19:11 UTC, sakhnik requested changes

2021-05-23 19:11 UTC, sakhnik commented on autoload/nvimgdb.vim
> +    \  'on_exit': {j,c,e -> execute(printf("if c == 0 | sil! bw! | endif" .
Pretty much action already. Would you be able to put it all into a function either in vimscript `nvimgdb#` or in Lua `NvimGdb`?

2021-05-24 05:24 UTC, kevinhwang91 commented
Pushed, if everything is fine, I will squash the commits.

2021-05-24 06:41 UTC, sakhnik commented
Thanks, that's perfect! I guess there's no need to squash the commits, the plugin is functional either way.

2021-05-24 06:41 UTC, merged