Don't force temp files to be created in /tmp
sakhnik/nvim-gdb pull request #189
Opened 2023-05-19 16:51 UTC by ajpaon

On some platforms, like termux on android, `/tmp` is inaccessible. If we remove the `/tmp` prefix on the templates and instead set the `--tmpdir` flag, `mktemp` will use `$TMPDIR`, which on termux is set to `/data/data/com.termux/files/usr/tmp`

On my debian box where `TMPDIR` is unset it falls back to `/tmp`.

From the manpage:

```
> -p DIR, --tmpdir[=DIR]
>   interpret TEMPLATE relative to DIR; if DIR is not specified, use
>   $TMPDIR if set, else /tmp.
```

BTW, the code that handles this is here: http://git.savannah.gnu.org/cgit/coreutils.git/tree/src/mktemp.c#n286

2023-05-22 12:50 UTC, sakhnik commented
Thanks for the suggestion. Apparently, this can't be done in MacOS: https://github.com/sakhnik/nvim-gdb/actions/runs/5026479605/jobs/9050865435?pr=189
Could you please take a look at the issue and maybe implement a fallback to /tmp?

2023-05-22 12:51 UTC, sakhnik requested changes

2023-05-22 12:51 UTC, sakhnik commented on test/all.sh
> +tmpDir="$(mktemp -d --tmpdir nvim-gdb-test.XXXXXX)"
Unfortunately, doesn't work in MacOS: https://github.com/sakhnik/nvim-gdb/actions/runs/5026479605/jobs/9050865435?pr=189

2023-05-22 21:02 UTC, ajpaon commented
I switched `--tmpdir` to `-t`, which is supported on both platforms (though deprecated on linux) and has the same effect in this scenario.

2023-05-22 21:05 UTC, ajpaon commented
Comparison of the two options on linux (termux):

```
-p DIR, --tmpdir[=DIR]
              interpret TEMPLATE relative to DIR; if DIR is not specified, use
              $TMPDIR if set, else /tmp.  With this option, TEMPLATE must not
              be an absolute name; unlike with -t, TEMPLATE may contain
              slashes, but mktemp creates only the final component

       -t     interpret TEMPLATE as a single file name component, relative to
              a directory: $TMPDIR, if set; else the directory specified via
              -p; else /tmp [deprecated]
```

and macos:

```
  -t prefix
           Generate a template (using the supplied prefix and TMPDIR if set)
           to create a filename template.
```

2023-05-23 07:53 UTC, merged

2023-05-23 07:54 UTC, sakhnik commented
Thanks, I appreciate it!